Genome: "hg19"
BigWig:
  binSize: "10"
  normalizeUsing: "RPKM"
  extendReads: "200"
  effectiveGenomeSize: "2827437033"
MACS2:
  format: "AUTO"
  genome: "hs"
  genome-size: 2.7e9
  qvalue: 0.05
  extsize: 200
